try moving comile steps to test-compile & test file looks for custom .sh file

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -2,17 +2,10 @@
 
 multi_bin=/tmp/buildpacks/custom/bin
 
-detect_files=$(source $multi_bin/detect)
-if [ $? != 0 ]; then
+if [[ -f $1/buildpack-multi-test.sh ]]; then
+  source $1/buildpack-multi-test.sh
+  exit $?
+else
+  echo "buildpack-multi-test.sh not found"
   exit 1
 fi
-
-compile_packs=$(source $multi_bin/compile)
-if [ $? != 0 ]; then
-  exit 1
-fi
-
-BUILDPACK_MULTI_TEST_CMD=${BUILDPACK_MULTI_TEST_CMD:-"echo buildpack_multi_test_cmd_missing"}
-eval $BUILDPACK_MULTI_TEST_CMD
-
-exit $?
