test test-compile in one

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -2,27 +2,32 @@
 
 echo 'Running buildpack-multi test'
 
-dir=/tmp/build
+echo "arg1 $0"
+echo "arg1 $1"
+echo "arg1 $2"
+echo "arg1 $3"
 
-if [[ -f $dir/buildpack-multi-test.sh ]]; then
-  BP_MULTI_DIR="1"
-else
-  BP_MULTI_TEST="0"
-fi
-
-for BUILDPACK in $(cat $dir/.buildpacks); do
-  if [ "$BP_MULTI_TEST" = "1" ]; then
-    echo "Running found $dir/buildpack-multi-test file"
-    . $dir/buildpack-multi-test.sh $dir "i" $dir
-    if [ $? != 0 ]; then
-      echo "Running buildpack-multi-test failed"
-      exit 1
-    fi
-  else
-    echo "buildpack-multi-test file not found"
-  fi
-done
-
-if [ "$BP_MULTI_TEST" = "1" ]; then
-  . $dir/buildpack-multi-test.sh $dir "f"
-fi
+# dir=/tmp/build
+#
+# if [[ -f $dir/buildpack-multi-test.sh ]]; then
+#   BP_MULTI_DIR="1"
+# else
+#   BP_MULTI_TEST="0"
+# fi
+#
+# for BUILDPACK in $(cat $dir/.buildpacks); do
+#   if [ "$BP_MULTI_TEST" = "1" ]; then
+#     echo "Running found $dir/buildpack-multi-test file"
+#     . $dir/buildpack-multi-test.sh $dir "i" $dir
+#     if [ $? != 0 ]; then
+#       echo "Running buildpack-multi-test failed"
+#       exit 1
+#     fi
+#   else
+#     echo "buildpack-multi-test file not found"
+#   fi
+# done
+#
+# if [ "$BP_MULTI_TEST" = "1" ]; then
+#   . $dir/buildpack-multi-test.sh $dir "f"
+# fi
diff --git a/bin/test-compile b/bin/test-compile
--- a/bin/test-compile
+++ b/bin/test-compile
@@ -1,15 +1,92 @@
 #!/usr/bin/env bash
 
-BP_MULTI_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
+# BP_MULTI_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
 
-echo 'buildpack-multi test-compile - detect buildpacks'
-detect_files=$(. $BP_MULTI_DIR/bin/detect $1)
-if [ $? != 0 ]; then
-  exit 1
-fi
+# echo 'buildpack-multi test-compile - detect buildpacks'
+# detect_files=$(. $BP_MULTI_DIR/bin/detect $1)
+# if [ $? != 0 ]; then
+#   exit 1
+# fi
+#
+# echo 'buildpack-multi test-compile - compile buildpacks'
+# compile_packs=$(. $BP_MULTI_DIR/bin/compile $1 $2 $3)
+# if [ $? != 0 ]; then
+#   exit 1
+# fi
+#!/usr/bin/env bash
 
-echo 'buildpack-multi test-compile - compile buildpacks'
-compile_packs=$(. $BP_MULTI_DIR/bin/compile $1 $2 $3)
-if [ $? != 0 ]; then
-  exit 1
+set -e
+
+unset GIT_DIR
+
+for BUILDPACK in $(cat $1/.buildpacks); do
+  dir=$(mktemp -t buildpackXXXXX)
+  rm -rf $dir
+
+  url=${BUILDPACK%#*}
+  branch=${BUILDPACK#*#}
+
+  if [ "$branch" == "$url" ]; then
+    branch=""
+  fi
+
+  if [ "$url" != "" ]; then
+    echo "=====> Downloading Buildpack: $url"
+
+    if [[ "$url" =~ \.tgz$ ]] || [[ "$url" =~ \.tgz\? ]]; then
+      mkdir -p "$dir"
+      curl -s "$url" | tar xvz -C "$dir" >/dev/null 2>&1
+    else
+      git clone $url $dir >/dev/null 2>&1
+    fi
+    cd $dir
+
+    if [ "$branch" != "" ]; then
+      git checkout $branch >/dev/null 2>&1
+    fi
+
+    # we'll get errors later if these are needed and don't exist
+    chmod -f +x $dir/bin/{detect,compile,release} || true
+    if [[ -f $dir/bin/test ]]; then
+      chmod -f +x $dir/bin/test || true
+    fi
+    if [[ -f $dir/bin/test ]]; then
+      chmod -f +x $dir/bin/test-compile || true
+    fi
+
+    framework=$($dir/bin/detect $1)
+
+    if [ $? == 0 ]; then
+      echo "=====> Detected Framework: $framework"
+      if [[ -f $dir/bin/test-compile ]]; then
+        $dir/bin/test-compile $1 $2 $3
+      else
+        $dir/bin/compile $1 $2 $3
+      fi
+
+      if [ $? != 0 ]; then
+        exit 1
+      fi
+
+      # check if the buildpack left behind an environment for subsequent ones
+      if [ -e $dir/export ]; then
+        source $dir/export
+      fi
+
+      if [ -x $dir/bin/release ]; then
+        $dir/bin/release $1 > $1/last_pack_release.out
+      fi
+
+      if [[ -f $dir/bin/test ]]; then
+        $dir/bin/test $1 $2 $3
+      fi
+    else
+      echo "Couldn't detect any framework for this buildpack. Exiting."
+      exit 1
+    fi
+  fi
+done
+
+if [ -e $1/last_pack_release.out ]; then
+  echo "Using release configuration from last framework ($framework)."
 fi
